[build]
  publish = "dist"           # Build sonrası yayınlanacak klasör
  command = "npm run build"  # Build komutu

[build.environment]
  NODE_VERSION = "20"        # Node sürümü Netlify ile uyumlu

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
